In [1]:
from project_olist.config import RAW_DATA_DIR
import pandas
import numpy

dataframe_pedidos = pandas.read_csv(RAW_DATA_DIR / "olist_orders_dataset.csv")
dataframe_pedidos = dataframe_pedidos.rename(
    columns={
        "order_id": "id_pedido",
        "customer_id": "id_cliente",
        "order_status": "status_pedido",
        "order_purchase_timestamp": "data_criacao",
        "order_approved_at": "data_aprovacao_pagamento",
        "order_delivered_carrier_date": "data_postagem",
        "order_delivered_customer_date": "data_entrega",
        "order_estimated_delivery_date": "data_estimada_entrega"
    }
)

dataframe_pedidos.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id_pedido                 99441 non-null  str
 1   id_cliente                99441 non-null  str
 2   status_pedido             99441 non-null  str
 3   data_criacao              99441 non-null  str
 4   data_aprovacao_pagamento  99281 non-null  str
 5   data_postagem             97658 non-null  str
 6   data_entrega              96476 non-null  str
 7   data_estimada_entrega     99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

In [2]:
dataframe_pedidos = dataframe_pedidos.drop_duplicates(subset="id_pedido")

dataframe_pedidos.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id_pedido                 99441 non-null  str
 1   id_cliente                99441 non-null  str
 2   status_pedido             99441 non-null  str
 3   data_criacao              99441 non-null  str
 4   data_aprovacao_pagamento  99281 non-null  str
 5   data_postagem             97658 non-null  str
 6   data_entrega              96476 non-null  str
 7   data_estimada_entrega     99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

In [3]:
dataframe_pedidos.sample(n=5)

,id_pedido,id_cliente,status_pedido,data_criacao,data_aprovacao_pagamento,data_postagem,data_entrega,data_estimada_entrega
47058,88543da9ad238e70098166896bf9ea06,8c36552c8308b0ba88cd19ba9fa14597,delivered,2018-08-14 10:47:21,2018-08-14 11:04:24,2018-08-15 14:54:00,2018-08-16 19:56:40,2018-08-17 00:00:00
29002,57b9cf4a37a14014639920e1f6d81e52,7ae471bc92b0ecb06c812292ffef849b,delivered,2018-01-23 22:47:46,2018-01-23 22:57:25,2018-01-25 00:33:16,2018-02-06 19:00:54,2018-02-16 00:00:00
25985,4b7687ed745753cae867364fb541ae37,da4d4e51ac3fda2a636979be0958d1d9,delivered,2017-12-03 18:39:38,2017-12-03 18:53:40,2017-12-06 16:51:37,2017-12-14 15:16:41,2018-01-02 00:00:00
62707,b87024ec4da1b89f2002223e52f25597,b006b2bca340326ecb17cfeaff935e75,delivered,2017-08-14 21:59:30,2017-08-14 23:04:00,2017-08-16 17:04:39,2017-08-30 21:24:00,2017-09-18 00:00:00
74006,99cca049bdfcd6019f861465e6b9261e,17b162e0b8cd336b0c7624a8e463076f,delivered,2018-07-20 19:02:01,2018-07-20 19:35:17,2018-07-24 07:12:00,2018-07-30 12:25:25,2018-08-16 00:00:00

In [4]:
dataframe_pedidos["data_criacao"] = pandas.to_datetime(dataframe_pedidos["data_criacao"]).dt.normalize()
dataframe_pedidos["data_aprovacao_pagamento"] = pandas.to_datetime(dataframe_pedidos["data_aprovacao_pagamento"]).dt.normalize()
dataframe_pedidos["data_postagem"] = pandas.to_datetime(dataframe_pedidos["data_postagem"]).dt.normalize()
dataframe_pedidos["data_entrega"] = pandas.to_datetime(dataframe_pedidos["data_entrega"]).dt.normalize()
dataframe_pedidos["data_estimada_entrega"] = pandas.to_datetime(dataframe_pedidos["data_estimada_entrega"]).dt.normalize()

dataframe_pedidos.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id_pedido                 99441 non-null  str
 1   id_cliente                99441 non-null  str
 2   status_pedido             99441 non-null  str
 3   data_criacao              99441 non-null  datetime64[us]
 4   data_aprovacao_pagamento  99281 non-null  datetime64[us]
 5   data_postagem             97658 non-null  datetime64[us]
 6   data_entrega              96476 non-null  datetime64[us]
 7   data_estimada_entrega     99441 non-null  datetime64[us]
dtypes: datetime64[us](5), str(3)
memory usage: 6.1 MB

In [5]:
dataframe_pedidos["dias_para_entrega_estimada"] = (
    (dataframe_pedidos["data_estimada_entrega"] - dataframe_pedidos["data_criacao"]).dt.days
)

dataframe_pedidos["dias_para_entrega_estimada"] = (
    dataframe_pedidos["dias_para_entrega_estimada"]
        .fillna(dataframe_pedidos["dias_para_entrega_estimada"].median())
)

dataframe_pedidos["dias_para_entrega_estimada"] = (
    dataframe_pedidos["dias_para_entrega_estimada"].astype("int")
)

dataframe_pedidos["dias_para_postagem"] = (
    (dataframe_pedidos["data_postagem"] - dataframe_pedidos["data_criacao"]).dt.days
)

dataframe_pedidos["dias_para_postagem"] = (
    dataframe_pedidos["dias_para_postagem"]
        .fillna(dataframe_pedidos["dias_para_postagem"].median())
)

dataframe_pedidos["dias_para_postagem"] = (
    dataframe_pedidos["dias_para_postagem"].astype("int")
)

dataframe_pedidos["dias_para_entrega"] = (
    (dataframe_pedidos["data_entrega"] - dataframe_pedidos["data_criacao"]).dt.days
)

dataframe_pedidos["dias_para_entrega"] = (
    dataframe_pedidos["dias_para_entrega"]
        .fillna(dataframe_pedidos["dias_para_entrega"].median())
)

dataframe_pedidos["dias_para_entrega"] = (
    dataframe_pedidos["dias_para_entrega"].astype("int")
)

dataframe_pedidos.sample(n=5)

,id_pedido,id_cliente,status_pedido,data_criacao,data_aprovacao_pagamento,data_postagem,data_entrega,data_estimada_entrega,dias_para_entrega_estimada,dias_para_postagem,dias_para_entrega
22253,17a64f4aa50ee9ab751db1cfb720776f,8c3cd248a2635e7b2e32ecc118d8fdb2,delivered,2017-11-15,2017-11-17,2017-11-17,2017-11-21,2017-11-29,14,2,6
15312,abc61b624c9611e850c2f84c17acc0c3,f91986733d4a59b9fa58b33468548c70,delivered,2018-03-14,2018-03-14,2018-03-15,2018-04-03,2018-04-02,19,1,20
73799,724ce270686637620b2fdeb626828db6,6b5584cbcf69fe02b86db187f9a463c3,delivered,2018-07-14,2018-07-14,2018-07-16,2018-07-23,2018-07-31,17,2,9
24221,0653cf037de0812e8ba775b4a0ea9c2f,bf140fe2e3a26db29d95589b4e03b3ac,delivered,2018-01-11,2018-01-11,2018-01-12,2018-01-23,2018-02-07,27,1,12
25532,34edba1d39c09cb41fd226b21f2116c2,fb67b1f519b9850cc4f21452d9e5a586,delivered,2018-03-15,2018-03-15,2018-03-16,2018-03-19,2018-03-27,12,1,4

In [6]:
dataframe_pedidos.describe()

,data_criacao,data_aprovacao_pagamento,data_postagem,data_entrega,data_estimada_entrega,dias_para_entrega_estimada,dias_para_postagem,dias_para_entrega
count,99441,99281,97658,96476,99441,99441.000000,99441.000000,99441.000000
mean,2017-12-30 17:26:56.616888,2017-12-31 05:20:33.553247,2018-01-04 06:13:53.848737,2018-01-13 19:24:32.449106,2018-01-24 03:08:37.730111,24.403948,3.198731,12.422874
min,2016-09-04 00:00:00,2016-09-15 00:00:00,2016-10-08 00:00:00,2016-10-11 00:00:00,2016-09-30 00:00:00,2.000000,-171.000000,0.000000
25%,2017-09-12 00:00:00,2017-09-12 00:00:00,2017-09-15 00:00:00,2017-09-25 00:00:00,2017-10-03 00:00:00,19.000000,1.000000,7.000000
50%,2018-01-18 00:00:00,2018-01-19 00:00:00,2018-01-24 00:00:00,2018-02-02 00:00:00,2018-02-15 00:00:00,24.000000,2.000000,10.000000
75%,2018-05-04 00:00:00,2018-05-04 00:00:00,2018-05-08 00:00:00,2018-05-15 00:00:00,2018-05-25 00:00:00,29.000000,4.000000,15.000000
max,2018-10-17 00:00:00,2018-09-03 00:00:00,2018-09-11 00:00:00,2018-10-17 00:00:00,2018-11-12 00:00:00,156.000000,126.000000,210.000000
std,NaN,NaN,NaN,NaN,NaN,8.829569,3.596876,9.421504

In [7]:
dataframe_pedidos = dataframe_pedidos[dataframe_pedidos["dias_para_postagem"] >= 0]

dataframe_pedidos.describe()

,data_criacao,data_aprovacao_pagamento,data_postagem,data_entrega,data_estimada_entrega,dias_para_entrega_estimada,dias_para_postagem,dias_para_entrega
count,99439,99279,97656,96474,99439,99439.000000,99439.000000,99439.000000
mean,2017-12-30 17:20:45.133197,2017-12-31 05:14:22.333424,2018-01-04 06:10:18.432047,2018-01-13 19:18:18.650413,2018-01-24 03:02:39.112621,24.404097,3.200555,12.422943
min,2016-09-04 00:00:00,2016-09-15 00:00:00,2016-10-08 00:00:00,2016-10-11 00:00:00,2016-09-30 00:00:00,2.000000,0.000000,0.000000
25%,2017-09-12 00:00:00,2017-09-12 00:00:00,2017-09-15 00:00:00,2017-09-25 00:00:00,2017-10-03 00:00:00,19.000000,1.000000,7.000000
50%,2018-01-18 00:00:00,2018-01-19 00:00:00,2018-01-24 00:00:00,2018-02-02 00:00:00,2018-02-15 00:00:00,24.000000,2.000000,10.000000
75%,2018-05-04 00:00:00,2018-05-04 00:00:00,2018-05-08 00:00:00,2018-05-15 00:00:00,2018-05-25 00:00:00,29.000000,4.000000,15.000000
max,2018-10-17 00:00:00,2018-09-03 00:00:00,2018-09-11 00:00:00,2018-10-17 00:00:00,2018-11-12 00:00:00,156.000000,126.000000,210.000000
std,NaN,NaN,NaN,NaN,NaN,8.829567,3.554165,9.421582

In [8]:
dataframe_pedidos = dataframe_pedidos.drop(
    columns=[
        "data_criacao",
        "data_aprovacao_pagamento",
        "data_postagem",
        "data_entrega",
        "data_estimada_entrega"
    ]
)

dataframe_pedidos.info()

<class 'pandas.DataFrame'>
Index: 99439 entries, 0 to 99440
Data columns (total 6 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id_pedido                   99439 non-null  str
 1   id_cliente                  99439 non-null  str
 2   status_pedido               99439 non-null  str
 3   dias_para_entrega_estimada  99439 non-null  int64
 4   dias_para_postagem          99439 non-null  int64
 5   dias_para_entrega           99439 non-null  int64
dtypes: int64(3), str(3)
memory usage: 5.3 MB

In [9]:
dataframe_pedidos.sample(n=5)

,id_pedido,id_cliente,status_pedido,dias_para_entrega_estimada,dias_para_postagem,dias_para_entrega
43540,0f2feb76d52c8e1be73daf8769a393e8,c849d0ca6e024f4f72ea8eace58ee21d,delivered,32,1,7
41390,ace9787c2536f487f1491bac9707fd67,5d7f01a5cbb98291c5bc6ab3f93be0ed,delivered,16,6,9
15143,b2d30dfaf7114de8ab3f737d062032fe,b498a2691a3bd3fcc7107cbdf3d5633a,delivered,48,3,15
89902,4a361afb3224a82115cdd08fb60b0528,32a15485330a0e465c45b9e437ca51fe,delivered,14,1,3
4656,8b47e7e04a986e036f10ab10bae91a4b,afe72ed049ec9d0b2197c39828695745,delivered,21,4,13

In [10]:
dataframe_pedidos["status_pedido"].unique()

<StringArray>
[  'delivered',    'invoiced',     'shipped',  'processing', 'unavailable',
    'canceled',     'created',    'approved']
Length: 8, dtype: str

In [11]:
dataframe_pedidos["status_pedido"] = dataframe_pedidos["status_pedido"].map({
    "delivered": "entregue",
    "invoiced": "faturado",
    "shipped": "enviado",
    "processing": "processando",
    "unavailable": "indisponível",
    "canceled": "cancelado",
    "created": "criado",
    "approved": "aprovado"
})

In [12]:
dataframe_pedidos.describe()

       dias_para_entrega_estimada  dias_para_postagem  dias_para_entrega
count                99439.000000        99439.000000       99439.000000
mean                    24.404097            3.200555          12.422943
std                      8.829567            3.554165           9.421582
min                      2.000000            0.000000           0.000000
25%                     19.000000            1.000000           7.000000
50%                     24.000000            2.000000          10.000000
75%                     29.000000            4.000000          15.000000
max                    156.000000          126.000000         210.000000

In [15]:
from project_olist.config import PROCESSED_DATA_DIR

dataframe_pedidos.to_csv(PROCESSED_DATA_DIR / "pedidos.csv", index=False)