In [1]:
from project_olist.config import PROCESSED_DATA_DIR
import pandas

dataframe_avaliacoes = pandas.read_csv(PROCESSED_DATA_DIR / "avaliacoes.csv")
dataframe_pedidos = pandas.read_csv(PROCESSED_DATA_DIR / "pedidos.csv")
dataframe_itens_pedidos = pandas.read_csv(PROCESSED_DATA_DIR / "itens_pedidos.csv") 
dataframe_metricas_produtos = pandas.read_csv(PROCESSED_DATA_DIR / "produtos_metricas.csv")

In [2]:
dataframe_avaliacoes.info()

<class 'pandas.DataFrame'>
RangeIndex: 98156 entries, 0 to 98155
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_avaliacao         98156 non-null  str
 1   id_pedido            98156 non-null  str
 2   pontuacao            98156 non-null  int64
 3   tempo_resposta_dias  98156 non-null  int64
 4   cliente_satisfeito   98156 non-null  int64
dtypes: int64(3), str(2)
memory usage: 3.7 MB

In [3]:
dataframe_pedidos.info()

<class 'pandas.DataFrame'>
RangeIndex: 96476 entries, 0 to 96475
Data columns (total 6 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id_pedido                   96476 non-null  str
 1   id_cliente                  96476 non-null  str
 2   status_pedido               96476 non-null  str
 3   dias_para_entrega_estimada  96476 non-null  int64
 4   dias_para_postagem          96476 non-null  int64
 5   dias_para_entrega           96476 non-null  int64
dtypes: int64(3), str(3)
memory usage: 4.4 MB

In [4]:
dataframe_itens_pedidos.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id_pedido            112650 non-null  str
 1   id_item_pedido       112650 non-null  int64
 2   id_produto           112650 non-null  str
 3   id_vendedor          112650 non-null  str
 4   data_limite_entrega  112650 non-null  str
 5   preco                112650 non-null  float64
 6   frete                112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB

In [5]:
dataframe_metricas_produtos.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_produto       32951 non-null  str
 1   volume_vendas    32951 non-null  int64
 2   media_avaliacao  32951 non-null  float64
dtypes: float64(1), int64(1), str(1)
memory usage: 772.4 KB

In [6]:
dataframe_pedidos = dataframe_pedidos.merge(
    dataframe_avaliacoes,
    on="id_pedido",
    how="left"
)

dataframe_pedidos.info()

<class 'pandas.DataFrame'>
RangeIndex: 96476 entries, 0 to 96475
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id_pedido                   96476 non-null  str
 1   id_cliente                  96476 non-null  str
 2   status_pedido               96476 non-null  str
 3   dias_para_entrega_estimada  96476 non-null  int64
 4   dias_para_postagem          96476 non-null  int64
 5   dias_para_entrega           96476 non-null  int64
 6   id_avaliacao                95357 non-null  str
 7   pontuacao                   95357 non-null  float64
 8   tempo_resposta_dias         95357 non-null  float64
 9   cliente_satisfeito          95357 non-null  float64
dtypes: float64(3), int64(3), str(4)
memory usage: 7.4 MB

In [7]:
dataframe_pedidos["pontuacao"] = (
    dataframe_pedidos["pontuacao"].fillna(
        dataframe_pedidos["pontuacao"].median()
    )
)

dataframe_pedidos["tempo_resposta_dias"] = (
    dataframe_pedidos["tempo_resposta_dias"].fillna(
        dataframe_pedidos["tempo_resposta_dias"].median()
    )
)

dataframe_pedidos["cliente_satisfeito"] = (
    dataframe_pedidos["cliente_satisfeito"].fillna(
        dataframe_pedidos["cliente_satisfeito"].median()
    )
)

dataframe_pedidos.info()

<class 'pandas.DataFrame'>
RangeIndex: 96476 entries, 0 to 96475
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id_pedido                   96476 non-null  str
 1   id_cliente                  96476 non-null  str
 2   status_pedido               96476 non-null  str
 3   dias_para_entrega_estimada  96476 non-null  int64
 4   dias_para_postagem          96476 non-null  int64
 5   dias_para_entrega           96476 non-null  int64
 6   id_avaliacao                95357 non-null  str
 7   pontuacao                   96476 non-null  float64
 8   tempo_resposta_dias         96476 non-null  float64
 9   cliente_satisfeito          96476 non-null  float64
dtypes: float64(3), int64(3), str(4)
memory usage: 7.4 MB

In [8]:
dataframe_pedidos = dataframe_pedidos.rename(
    columns={
        "pontuacao": "pontuacao_avaliacao",
        "tempo_resposta_dias": "tempo_resposta_dias_avaliacao"
    }
)

dataframe_pedidos.info()

<class 'pandas.DataFrame'>
RangeIndex: 96476 entries, 0 to 96475
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id_pedido                      96476 non-null  str
 1   id_cliente                     96476 non-null  str
 2   status_pedido                  96476 non-null  str
 3   dias_para_entrega_estimada     96476 non-null  int64
 4   dias_para_postagem             96476 non-null  int64
 5   dias_para_entrega              96476 non-null  int64
 6   id_avaliacao                   95357 non-null  str
 7   pontuacao_avaliacao            96476 non-null  float64
 8   tempo_resposta_dias_avaliacao  96476 non-null  float64
 9   cliente_satisfeito             96476 non-null  float64
dtypes: float64(3), int64(3), str(4)
memory usage: 7.4 MB

In [9]:
dataframe_metricas_pedidos = dataframe_pedidos.copy()

dataframe_metricas_pedidos = dataframe_metricas_pedidos.merge(
    dataframe_itens_pedidos,
    on="id_pedido",
    how="inner"
)

dataframe_metricas_pedidos.info()

<class 'pandas.DataFrame'>
RangeIndex: 110195 entries, 0 to 110194
Data columns (total 16 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   id_pedido                      110195 non-null  str
 1   id_cliente                     110195 non-null  str
 2   status_pedido                  110195 non-null  str
 3   dias_para_entrega_estimada     110195 non-null  int64
 4   dias_para_postagem             110195 non-null  int64
 5   dias_para_entrega              110195 non-null  int64
 6   id_avaliacao                   108820 non-null  str
 7   pontuacao_avaliacao            110195 non-null  float64
 8   tempo_resposta_dias_avaliacao  110195 non-null  float64
 9   cliente_satisfeito             110195 non-null  float64
 10  id_item_pedido                 110195 non-null  int64
 11  id_produto                     110195 non-null  str
 12  id_vendedor                    110195 non-null  str
 13  data_limite_entrega            110195 non-null  str
 14  preco                          110195 non-null  float64
 15  frete                          110195 non-null  float64
dtypes: float64(5), int64(4), str(7)
memory usage: 13.5 MB

In [10]:
dataframe_metricas_pedidos = dataframe_metricas_pedidos.merge(
    dataframe_metricas_produtos,
    on="id_produto",
    how="left"
)

dataframe_metricas_pedidos.info()

<class 'pandas.DataFrame'>
RangeIndex: 110195 entries, 0 to 110194
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   id_pedido                      110195 non-null  str
 1   id_cliente                     110195 non-null  str
 2   status_pedido                  110195 non-null  str
 3   dias_para_entrega_estimada     110195 non-null  int64
 4   dias_para_postagem             110195 non-null  int64
 5   dias_para_entrega              110195 non-null  int64
 6   id_avaliacao                   108820 non-null  str
 7   pontuacao_avaliacao            110195 non-null  float64
 8   tempo_resposta_dias_avaliacao  110195 non-null  float64
 9   cliente_satisfeito             110195 non-null  float64
 10  id_item_pedido                 110195 non-null  int64
 11  id_produto                     110195 non-null  str
 12  id_vendedor                    110195 non-null  str
 13  data_limite_entrega            110195 non-null  str
 14  preco                          110195 non-null  float64
 15  frete                          110195 non-null  float64
 16  volume_vendas                  110195 non-null  int64
 17  media_avaliacao                110195 non-null  float64
dtypes: float64(6), int64(5), str(7)
memory usage: 15.1 MB

In [11]:
dataframe_metricas_pedidos = dataframe_metricas_pedidos.groupby(by="id_pedido", as_index=False).agg(
    {
        "preco": "sum",
        "frete": "sum",
        "volume_vendas": "mean",
        "media_avaliacao": "mean"
    }
)

dataframe_metricas_pedidos = dataframe_metricas_pedidos.rename(
    columns={
        "preco": "preco_total_itens",
        "frete": "preco_total_frete",
        "volume_vendas": "media_volume_vendas_produtos",
        "media_avaliacao": "media_avaliacao_produtos"
    }
)

dataframe_metricas_pedidos.info()

<class 'pandas.DataFrame'>
RangeIndex: 96476 entries, 0 to 96475
Data columns (total 5 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   id_pedido                     96476 non-null  str
 1   preco_total_itens             96476 non-null  float64
 2   preco_total_frete             96476 non-null  float64
 3   media_volume_vendas_produtos  96476 non-null  float64
 4   media_avaliacao_produtos      96476 non-null  float64
dtypes: float64(4), str(1)
memory usage: 3.7 MB

In [12]:
dataframe_metricas_pedidos.to_csv(PROCESSED_DATA_DIR / "pedidos_metricas.csv")

In [13]:
dataframe_pedidos = dataframe_pedidos.merge(
    dataframe_metricas_pedidos,
    on="id_pedido",
    how="left"
)

dataframe_pedidos.info()

<class 'pandas.DataFrame'>
RangeIndex: 96476 entries, 0 to 96475
Data columns (total 14 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id_pedido                      96476 non-null  str
 1   id_cliente                     96476 non-null  str
 2   status_pedido                  96476 non-null  str
 3   dias_para_entrega_estimada     96476 non-null  int64
 4   dias_para_postagem             96476 non-null  int64
 5   dias_para_entrega              96476 non-null  int64
 6   id_avaliacao                   95357 non-null  str
 7   pontuacao_avaliacao            96476 non-null  float64
 8   tempo_resposta_dias_avaliacao  96476 non-null  float64
 9   cliente_satisfeito             96476 non-null  float64
 10  preco_total_itens              96476 non-null  float64
 11  preco_total_frete              96476 non-null  float64
 12  media_volume_vendas_produtos   96476 non-null  float64
 13  media_avaliacao_produtos       96476 non-null  float64
dtypes: float64(7), int64(3), str(4)
memory usage: 10.3 MB

In [14]:
dataframe_pedidos.sample(n=5)

,id_pedido,id_cliente,status_pedido,dias_para_entrega_estimada,dias_para_postagem,dias_para_entrega,id_avaliacao,pontuacao_avaliacao,tempo_resposta_dias_avaliacao,cliente_satisfeito,preco_total_itens,preco_total_frete,media_volume_vendas_produtos,media_avaliacao_produtos
18832,20d74f313f0dccb9b27b7865951126fe,74935c66741cfcde4ca7e0094d94a406,entregue,28,2,17,5a5990f95538088017a32c9f9b768829,4.0,1.0,1.0,79.90,19.53,46.0,4.200000
44831,fa1504a98e3482c59bb07d3024a15b14,1142984916495fad0d7693eee6007457,entregue,3,1,2,af309b3491c576ce38796cdc38a2974d,5.0,0.0,1.0,18.89,7.39,1.0,5.000000
39344,aff043b28dfff4c65665fb42597daf94,996e0d7f08d29b4301784932a81f2132,entregue,18,0,1,b8bdf5bf368720a71c0222bf16d9b1d3,5.0,0.0,1.0,166.99,13.72,51.0,3.940000
64610,5afac0b7cff137da6d13251afc7329c9,e0b4c1b6c6de01d78862c72eea6b24dd,entregue,27,1,22,eb3f72db4b2aa00cf3b0d170e3f0ebb9,5.0,1.0,1.0,44.99,28.75,1.0,5.000000
36006,b8fe1ee18bb4fc8242cafbc4d3edb987,e8999e45e374e1ce4ff7ef09d5995931,entregue,25,14,42,92e9cb73c715259fdbe3aeebff10a2a3,5.0,0.0,1.0,70.90,26.82,26.0,3.961538

In [15]:
dataframe_pedidos["media_avaliacao_produtos"] = dataframe_pedidos["media_avaliacao_produtos"].round(2)
dataframe_pedidos["media_volume_vendas_produtos"] = dataframe_pedidos["media_volume_vendas_produtos"].round(2)

dataframe_pedidos.sample(n=5)

,id_pedido,id_cliente,status_pedido,dias_para_entrega_estimada,dias_para_postagem,dias_para_entrega,id_avaliacao,pontuacao_avaliacao,tempo_resposta_dias_avaliacao,cliente_satisfeito,preco_total_itens,preco_total_frete,media_volume_vendas_produtos,media_avaliacao_produtos
39295,0ba555009a855c3f87f818f23b4ccdbd,4b7395d051260eca36885f07f32b5f73,entregue,23,4,9,f0e07992f10c33e5c675dddb11365db3,4.0,3.0,1.0,159.00,21.53,32.0,4.16
88288,d44913f6177d1b8a369a477ab2823aa2,006431d77c665533ac99b501d8a6ab06,entregue,11,1,3,183b1821afc6ae08083191fa364a7698,5.0,4.0,1.0,220.64,15.92,13.0,4.26
53957,cba6625a547cd5ad8a968733b3e23d8d,3cf092136e989db3a73751c5de94d633,entregue,20,4,8,7b5382cfc775847c55101b9d8fe910e8,5.0,2.0,1.0,89.99,9.44,260.0,4.08
24214,12aba4fdeb04e5cca1132f86f2bda749,ff785d347271a777a570f540796d284d,entregue,21,2,4,9d3838017d22783aa67ba9c557b8c43b,5.0,0.0,1.0,109.90,17.02,2.0,5.00
57464,2d5a9031ce30f2732d18bb3722b887a4,1fa1869a410018e63e73c5a1fe358492,entregue,39,2,10,a2e8b4e665acb20e3882024253228712,5.0,1.0,1.0,69.90,17.74,15.0,4.47

In [16]:
dataframe_pedidos["preco_total_pedido"] = dataframe_pedidos["preco_total_itens"] + dataframe_pedidos["preco_total_frete"]

In [17]:
dataframe_clientes = pandas.read_csv(PROCESSED_DATA_DIR / "clientes.csv")

dataframe_pedidos = dataframe_pedidos.merge(
    dataframe_clientes,
    on="id_cliente",
    how="left"
)

dataframe_pedidos.info()

<class 'pandas.DataFrame'>
RangeIndex: 96476 entries, 0 to 96475
Data columns (total 19 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id_pedido                      96476 non-null  str
 1   id_cliente                     96476 non-null  str
 2   status_pedido                  96476 non-null  str
 3   dias_para_entrega_estimada     96476 non-null  int64
 4   dias_para_postagem             96476 non-null  int64
 5   dias_para_entrega              96476 non-null  int64
 6   id_avaliacao                   95357 non-null  str
 7   pontuacao_avaliacao            96476 non-null  float64
 8   tempo_resposta_dias_avaliacao  96476 non-null  float64
 9   cliente_satisfeito             96476 non-null  float64
 10  preco_total_itens              96476 non-null  float64
 11  preco_total_frete              96476 non-null  float64
 12  media_volume_vendas_produtos   96476 non-null  float64
 13  media_avaliacao_produtos       96476 non-null  float64
 14  preco_total_pedido             96476 non-null  float64
 15  id_unico_cliente               96476 non-null  str
 16  prefixo_cep                    96476 non-null  int64
 17  cidade                         96476 non-null  str
 18  estado                         96476 non-null  str
dtypes: float64(8), int64(4), str(7)
memory usage: 14.0 MB

In [18]:
dataframe_geolocalizacoes = pandas.read_csv(PROCESSED_DATA_DIR / "geolocalizacoes.csv")

dataframe_pedidos = dataframe_pedidos.merge(
    dataframe_geolocalizacoes,
    left_on="prefixo_cep",
    right_on="prefixo_cep",
    how="left"
)

dataframe_pedidos.info()

<class 'pandas.DataFrame'>
RangeIndex: 96476 entries, 0 to 96475
Data columns (total 23 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id_pedido                      96476 non-null  str
 1   id_cliente                     96476 non-null  str
 2   status_pedido                  96476 non-null  str
 3   dias_para_entrega_estimada     96476 non-null  int64
 4   dias_para_postagem             96476 non-null  int64
 5   dias_para_entrega              96476 non-null  int64
 6   id_avaliacao                   95357 non-null  str
 7   pontuacao_avaliacao            96476 non-null  float64
 8   tempo_resposta_dias_avaliacao  96476 non-null  float64
 9   cliente_satisfeito             96476 non-null  float64
 10  preco_total_itens              96476 non-null  float64
 11  preco_total_frete              96476 non-null  float64
 12  media_volume_vendas_produtos   96476 non-null  float64
 13  media_avaliacao_produtos       96476 non-null  float64
 14  preco_total_pedido             96476 non-null  float64
 15  id_unico_cliente               96476 non-null  str
 16  prefixo_cep                    96476 non-null  int64
 17  cidade_x                       96476 non-null  str
 18  estado_x                       96476 non-null  str
 19  latitude                       96212 non-null  float64
 20  longitude                      96212 non-null  float64
 21  cidade_y                       96212 non-null  str
 22  estado_y                       96212 non-null  str
dtypes: float64(10), int64(4), str(9)
memory usage: 16.9 MB

In [21]:
dataframe_pedidos = dataframe_pedidos.drop(
    columns=[
        "id_unico_cliente",
        "prefixo_cep",
        "cidade_y",
        "estado_y"
    ]
).rename(
    columns={
        "cidade_x": "cidade",
        "estado_x": "estado"
    }
)

dataframe_pedidos.info()

<class 'pandas.DataFrame'>
RangeIndex: 96476 entries, 0 to 96475
Data columns (total 19 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id_pedido                      96476 non-null  str
 1   id_cliente                     96476 non-null  str
 2   status_pedido                  96476 non-null  str
 3   dias_para_entrega_estimada     96476 non-null  int64
 4   dias_para_postagem             96476 non-null  int64
 5   dias_para_entrega              96476 non-null  int64
 6   id_avaliacao                   95357 non-null  str
 7   pontuacao_avaliacao            96476 non-null  float64
 8   tempo_resposta_dias_avaliacao  96476 non-null  float64
 9   cliente_satisfeito             96476 non-null  float64
 10  preco_total_itens              96476 non-null  float64
 11  preco_total_frete              96476 non-null  float64
 12  media_volume_vendas_produtos   96476 non-null  float64
 13  media_avaliacao_produtos       96476 non-null  float64
 14  preco_total_pedido             96476 non-null  float64
 15  cidade                         96476 non-null  str
 16  estado                         96476 non-null  str
 17  latitude                       96212 non-null  float64
 18  longitude                      96212 non-null  float64
dtypes: float64(10), int64(3), str(6)
memory usage: 14.0 MB

In [22]:
dataframe_pedidos.describe()

,dias_para_entrega_estimada,dias_para_postagem,dias_para_entrega,pontuacao_avaliacao,tempo_resposta_dias_avaliacao,cliente_satisfeito,preco_total_itens,preco_total_frete,media_volume_vendas_produtos,media_avaliacao_produtos,preco_total_pedido,latitude,longitude
count,96476.000000,96476.000000,96476.000000,96476.000000,96476.000000,96476.000000,96476.000000,96476.000000,96476.000000,96476.000000,96476.000000,96212.000000,96212.000000
mean,24.372901,3.215774,12.496714,4.167689,2.561933,0.792415,137.042613,22.785489,35.931737,4.098619,159.828102,-21.201962,-46.188849
std,8.758141,3.567457,9.554784,1.278754,9.760162,0.405580,209.047131,21.559353,79.214425,0.790181,218.796217,5.600066,4.054145
min,3.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.850000,0.000000,1.000000,1.000000,9.590000,-33.689948,-72.668881
25%,19.000000,1.000000,7.000000,4.000000,1.000000,1.000000,45.900000,13.850000,2.000000,3.840000,61.850000,-23.589849,-48.118347
50%,24.000000,2.000000,10.000000,5.000000,1.000000,1.000000,86.575000,17.170000,7.000000,4.180000,105.280000,-22.924970,-46.631968
75%,29.000000,4.000000,16.000000,5.000000,3.000000,1.000000,149.900000,24.020000,27.000000,4.640000,176.270000,-20.140216,-43.625086
max,156.000000,126.000000,210.000000,5.000000,518.000000,1.000000,13440.000000,1794.960000,527.000000,5.000000,13664.080000,42.184003,-8.723762

In [23]:
dataframe_pedidos.to_csv(PROCESSED_DATA_DIR / "pedidos_com_metricas.csv", index=False)