In [15]:
from project_olist.config import RAW_DATA_DIR
import pandas

dataframe_pedidos = pandas.read_csv(RAW_DATA_DIR / "olist_orders_dataset.csv")

dataframe_pedidos = dataframe_pedidos.rename(
    columns={
        "order_id": "id_pedido",
        "customer_id": "id_cliente",
        "order_status": "status_pedido",
        "order_purchase_timestamp": "data_criacao",
        "order_approved_at": "data_aprovacao_pagamento",
        "order_delivered_carrier_date": "data_postagem",
        "order_delivered_customer_date": "data_entrega",
        "order_estimated_delivery_date": "data_estimada_entrega"
    }
)


dataframe_pedidos.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id_pedido                 99441 non-null  str
 1   id_cliente                99441 non-null  str
 2   status_pedido             99441 non-null  str
 3   data_criacao              99441 non-null  str
 4   data_aprovacao_pagamento  99281 non-null  str
 5   data_postagem             97658 non-null  str
 6   data_entrega              96476 non-null  str
 7   data_estimada_entrega     99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

In [16]:
dataframe_pedidos = dataframe_pedidos.drop_duplicates(subset="id_pedido")
dataframe_pedidos = dataframe_pedidos.reset_index(drop=True)

dataframe_pedidos.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id_pedido                 99441 non-null  str
 1   id_cliente                99441 non-null  str
 2   status_pedido             99441 non-null  str
 3   data_criacao              99441 non-null  str
 4   data_aprovacao_pagamento  99281 non-null  str
 5   data_postagem             97658 non-null  str
 6   data_entrega              96476 non-null  str
 7   data_estimada_entrega     99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

In [17]:
dataframe_pedidos.sample(n=5)

,id_pedido,id_cliente,status_pedido,data_criacao,data_aprovacao_pagamento,data_postagem,data_entrega,data_estimada_entrega
83170,56c93a3f93a1e7eb24ed51a6931dc488,d375691b753ce7bc99190bc08b813003,delivered,2017-05-26 07:36:03,2017-05-27 02:50:20,2017-05-30 11:34:23,2017-06-05 19:05:47,2017-06-20 00:00:00
69452,2a3a15442d770b77f30d1c2c02be3697,51ea9b5bc33e6a32904b5154b82c3837,delivered,2018-02-23 12:30:32,2018-02-23 12:49:18,2018-02-24 00:51:55,2018-03-24 11:16:46,2018-03-19 00:00:00
60991,5cc85e983f530b29858b3da0bfbc7228,b9b78d5b4aef308f92fbe5332cd81386,delivered,2017-09-01 01:08:15,2017-09-01 15:15:21,2017-09-04 16:18:08,2017-09-15 22:23:53,2017-09-20 00:00:00
37719,0948bd714f9f0ca68d9e70af5090d3f6,a2797e4ee0dd430eac06ca4b7eac8fde,delivered,2017-05-19 00:59:34,2017-05-19 01:30:21,2017-05-19 13:58:10,2017-05-23 18:39:30,2017-06-12 00:00:00
5422,75b7d764765f4cf3a5f03e7f3f35319f,f680ea76654a400d48f8ca6d16a20442,delivered,2018-01-22 15:54:09,2018-01-23 03:52:57,2018-01-23 19:47:44,2018-02-01 10:57:52,2018-02-19 00:00:00

In [18]:
dataframe_pedidos["status_pedido"].unique()

<StringArray>
[  'delivered',    'invoiced',     'shipped',  'processing', 'unavailable',
    'canceled',     'created',    'approved']
Length: 8, dtype: str

In [19]:
dataframe_pedidos["status_pedido"] = dataframe_pedidos["status_pedido"].map({
    "delivered": "entregue",
    "invoiced": "faturado",
    "shipped": "enviado",
    "processing": "processando",
    "unavailable": "indisponível",
    "canceled": "cancelado",
    "created": "criado",
    "approved": "aprovado"
})

In [20]:
dataframe_pedidos = dataframe_pedidos[dataframe_pedidos["status_pedido"] == "entregue"]

In [21]:
dataframe_pedidos["data_criacao"] = pandas.to_datetime(dataframe_pedidos["data_criacao"]).dt.normalize()
dataframe_pedidos["data_aprovacao_pagamento"] = pandas.to_datetime(dataframe_pedidos["data_aprovacao_pagamento"]).dt.normalize()
dataframe_pedidos["data_postagem"] = pandas.to_datetime(dataframe_pedidos["data_postagem"]).dt.normalize()
dataframe_pedidos["data_entrega"] = pandas.to_datetime(dataframe_pedidos["data_entrega"]).dt.normalize()
dataframe_pedidos["data_estimada_entrega"] = pandas.to_datetime(dataframe_pedidos["data_estimada_entrega"]).dt.normalize()

dataframe_pedidos.info()

<class 'pandas.DataFrame'>
Index: 96478 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id_pedido                 96478 non-null  str
 1   id_cliente                96478 non-null  str
 2   status_pedido             96478 non-null  str
 3   data_criacao              96478 non-null  datetime64[us]
 4   data_aprovacao_pagamento  96464 non-null  datetime64[us]
 5   data_postagem             96476 non-null  datetime64[us]
 6   data_entrega              96470 non-null  datetime64[us]
 7   data_estimada_entrega     96478 non-null  datetime64[us]
dtypes: datetime64[us](5), str(3)
memory usage: 6.6 MB

In [22]:
dataframe_pedidos["dias_para_entrega_estimada"] = (
    (dataframe_pedidos["data_estimada_entrega"] - dataframe_pedidos["data_criacao"]).dt.days
)

dataframe_pedidos["dias_para_entrega_estimada"] = (
    dataframe_pedidos["dias_para_entrega_estimada"]
        .fillna(dataframe_pedidos["dias_para_entrega_estimada"].median())
)

dataframe_pedidos["dias_para_entrega_estimada"] = (
    dataframe_pedidos["dias_para_entrega_estimada"].astype("int")
)

dataframe_pedidos["dias_para_postagem"] = (
    (dataframe_pedidos["data_postagem"] - dataframe_pedidos["data_criacao"]).dt.days
)

dataframe_pedidos["dias_para_postagem"] = (
    dataframe_pedidos["dias_para_postagem"]
        .fillna(dataframe_pedidos["dias_para_postagem"].median())
)

dataframe_pedidos["dias_para_postagem"] = (
    dataframe_pedidos["dias_para_postagem"].astype("int")
)

dataframe_pedidos["dias_para_entrega"] = (
    (dataframe_pedidos["data_entrega"] - dataframe_pedidos["data_criacao"]).dt.days
)

dataframe_pedidos["dias_para_entrega"] = (
    dataframe_pedidos["dias_para_entrega"]
        .fillna(dataframe_pedidos["dias_para_entrega"].median())
)

dataframe_pedidos["dias_para_entrega"] = (
    dataframe_pedidos["dias_para_entrega"].astype("int")
)

dataframe_pedidos.sample(n=5)

,id_pedido,id_cliente,status_pedido,data_criacao,data_aprovacao_pagamento,data_postagem,data_entrega,data_estimada_entrega,dias_para_entrega_estimada,dias_para_postagem,dias_para_entrega
12010,59b931645b38766a41bef9244d4ee476,3fcc0d2a43e27e5cd14cb2d881434777,entregue,2018-02-07,2018-02-07,2018-02-09,2018-02-11,2018-02-23,16,2,4
35751,9f47e04f95b2bba1442d5bbf0611733e,ed6d5239528458c1a45a3b15105ea27e,entregue,2017-05-09,2017-05-09,2017-05-16,2017-05-17,2017-05-25,16,7,8
75395,cfc558750a7ad84d94c1348dfd89543c,1af8d640c317b12571dc17ff39aa246c,entregue,2017-12-30,2017-12-30,2018-01-04,2018-01-11,2018-02-14,46,5,12
28733,8d13e349d7439353a923d49cc2598833,8d4958b500ee23ac8441f07a1a672e30,entregue,2017-11-27,2017-11-27,2017-11-28,2017-11-30,2017-12-11,14,1,3
77177,7f8cb0e907ae9dc4012ffab6fe6f738b,188ac4e8b7765d24cdb434112a99111f,entregue,2018-01-28,2018-01-30,2018-01-31,2018-02-04,2018-02-20,23,3,7

In [23]:
dataframe_pedidos.describe()

,data_criacao,data_aprovacao_pagamento,data_postagem,data_entrega,data_estimada_entrega,dias_para_entrega_estimada,dias_para_postagem,dias_para_entrega
count,96478,96464,96476,96470,96478,96478.000000,96478.000000,96478.000000
mean,2018-01-01 08:13:06.881983,2018-01-01 21:38:41.579034,2018-01-04 13:25:52.153903,2018-01-13 19:56:46.845651,2018-01-25 17:09:52.325711,24.372748,3.213893,12.496642
min,2016-09-15 00:00:00,2016-09-15 00:00:00,2016-10-08 00:00:00,2016-10-11 00:00:00,2016-10-04 00:00:00,3.000000,-171.000000,0.000000
25%,2017-09-14 00:00:00,2017-09-14 00:00:00,2017-09-18 00:00:00,2017-09-25 00:00:00,2017-10-05 00:00:00,19.000000,1.000000,7.000000
50%,2018-01-20 00:00:00,2018-01-22 00:00:00,2018-01-24 00:00:00,2018-02-02 00:00:00,2018-02-16 00:00:00,24.000000,2.000000,10.000000
75%,2018-05-05 00:00:00,2018-05-06 00:00:00,2018-05-08 00:00:00,2018-05-15 00:00:00,2018-05-28 00:00:00,29.000000,4.000000,16.000000
max,2018-08-29 00:00:00,2018-08-29 00:00:00,2018-09-11 00:00:00,2018-10-17 00:00:00,2018-10-25 00:00:00,156.000000,126.000000,210.000000
std,NaN,NaN,NaN,NaN,NaN,8.758144,3.611318,9.554702

In [24]:
dataframe_pedidos = dataframe_pedidos[dataframe_pedidos["dias_para_postagem"] >= 0]

dataframe_pedidos.describe()

,data_criacao,data_aprovacao_pagamento,data_postagem,data_entrega,data_estimada_entrega,dias_para_entrega_estimada,dias_para_postagem,dias_para_entrega
count,96476,96462,96474,96468,96476,96476.000000,96476.000000,96476.000000
mean,2018-01-01 08:06:46.882540,2018-01-01 21:32:22.526590,2018-01-04 13:22:14.635238,2018-01-13 19:50:33.063813,2018-01-25 17:03:45.531738,24.372901,3.215774,12.496714
min,2016-09-15 00:00:00,2016-09-15 00:00:00,2016-10-08 00:00:00,2016-10-11 00:00:00,2016-10-04 00:00:00,3.000000,0.000000,0.000000
25%,2017-09-14 00:00:00,2017-09-14 00:00:00,2017-09-18 00:00:00,2017-09-25 00:00:00,2017-10-05 00:00:00,19.000000,1.000000,7.000000
50%,2018-01-20 00:00:00,2018-01-22 00:00:00,2018-01-24 00:00:00,2018-02-02 00:00:00,2018-02-16 00:00:00,24.000000,2.000000,10.000000
75%,2018-05-05 00:00:00,2018-05-06 00:00:00,2018-05-08 00:00:00,2018-05-15 00:00:00,2018-05-28 00:00:00,29.000000,4.000000,16.000000
max,2018-08-29 00:00:00,2018-08-29 00:00:00,2018-09-11 00:00:00,2018-10-17 00:00:00,2018-10-25 00:00:00,156.000000,126.000000,210.000000
std,NaN,NaN,NaN,NaN,NaN,8.758141,3.567457,9.554784

In [25]:
dataframe_pedidos = dataframe_pedidos.drop(
    columns=[
        "data_criacao",
        "data_aprovacao_pagamento",
        "data_postagem",
        "data_entrega",
        "data_estimada_entrega"
    ]
)

dataframe_pedidos.info()

<class 'pandas.DataFrame'>
Index: 96476 entries, 0 to 99440
Data columns (total 6 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id_pedido                   96476 non-null  str
 1   id_cliente                  96476 non-null  str
 2   status_pedido               96476 non-null  str
 3   dias_para_entrega_estimada  96476 non-null  int64
 4   dias_para_postagem          96476 non-null  int64
 5   dias_para_entrega           96476 non-null  int64
dtypes: int64(3), str(3)
memory usage: 5.2 MB

In [26]:
dataframe_pedidos.sample(n=5)

,id_pedido,id_cliente,status_pedido,dias_para_entrega_estimada,dias_para_postagem,dias_para_entrega
59167,d8f3f6f587c473f30872ffdf8170fc6c,08c107b0b78e43fa0195263569937873,entregue,17,2,8
35401,bef0a9fd3674bdfdb2a292fab7793cfd,15ecd23b1acbeaad411b5e7fadb5b82a,entregue,23,2,19
42000,6b5c76c2c9615b42e0c2b7efb11b60d7,645d4fd3f4546d7c9592576665711186,entregue,24,14,21
90671,73cb429669ebb88bba7787201730c88e,17ace424038c433ea0cbcb88de1eaeb9,entregue,29,2,29
68775,9e766b8cbac373f4795d99c05f57514c,e46281bc93a3e0a5e9043f4a19dd541c,entregue,29,2,11

In [27]:
dataframe_pedidos.describe()

       dias_para_entrega_estimada  dias_para_postagem  dias_para_entrega
count                96476.000000        96476.000000       96476.000000
mean                    24.372901            3.215774          12.496714
std                      8.758141            3.567457           9.554784
min                      3.000000            0.000000           0.000000
25%                     19.000000            1.000000           7.000000
50%                     24.000000            2.000000          10.000000
75%                     29.000000            4.000000          16.000000
max                    156.000000          126.000000         210.000000

In [28]:
from project_olist.config import PROCESSED_DATA_DIR

dataframe_pedidos.to_csv(PROCESSED_DATA_DIR / "pedidos.csv", index=False)