In [77]:
from project_olist.config import PROCESSED_DATA_DIR
import pandas

dataframe_avaliacoes = pandas.read_csv(PROCESSED_DATA_DIR / "avaliacoes.csv")
dataframe_itens_pedidos = pandas.read_csv(PROCESSED_DATA_DIR / "itens_pedidos.csv") 
dataframe_produtos = pandas.read_csv(PROCESSED_DATA_DIR / "produtos.csv")

In [78]:
dataframe_avaliacoes.info()

<class 'pandas.DataFrame'>
RangeIndex: 98156 entries, 0 to 98155
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_avaliacao         98156 non-null  str
 1   id_pedido            98156 non-null  str
 2   pontuacao            98156 non-null  int64
 3   tempo_resposta_dias  98156 non-null  int64
 4   cliente_satisfeito   98156 non-null  int64
dtypes: int64(3), str(2)
memory usage: 3.7 MB

In [79]:
dataframe_itens_pedidos.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id_pedido            112650 non-null  str
 1   id_item_pedido       112650 non-null  int64
 2   id_produto           112650 non-null  str
 3   id_vendedor          112650 non-null  str
 4   data_limite_entrega  112650 non-null  str
 5   preco                112650 non-null  float64
 6   frete                112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB

In [80]:
dataframe_produtos.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_produto         32951 non-null  str
 1   categoria_produto  32341 non-null  str
dtypes: str(2)
memory usage: 515.0 KB

In [81]:
dataframe_produtos = dataframe_produtos.merge(
    dataframe_itens_pedidos,
    on="id_produto",
    how="left"
)

dataframe_produtos.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id_produto           112650 non-null  str
 1   categoria_produto    111047 non-null  str
 2   id_pedido            112650 non-null  str
 3   id_item_pedido       112650 non-null  int64
 4   id_vendedor          112650 non-null  str
 5   data_limite_entrega  112650 non-null  str
 6   preco                112650 non-null  float64
 7   frete                112650 non-null  float64
dtypes: float64(2), int64(1), str(5)
memory usage: 6.9 MB

In [82]:
dataframe_produtos = dataframe_produtos.merge(
    dataframe_avaliacoes,
    on="id_pedido",
    how="left"
)

dataframe_produtos.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 12 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id_produto           112650 non-null  str
 1   categoria_produto    111047 non-null  str
 2   id_pedido            112650 non-null  str
 3   id_item_pedido       112650 non-null  int64
 4   id_vendedor          112650 non-null  str
 5   data_limite_entrega  112650 non-null  str
 6   preco                112650 non-null  float64
 7   frete                112650 non-null  float64
 8   id_avaliacao         111146 non-null  str
 9   pontuacao            111146 non-null  float64
 10  tempo_resposta_dias  111146 non-null  float64
 11  cliente_satisfeito   111146 non-null  float64
dtypes: float64(5), int64(1), str(6)
memory usage: 10.3 MB

In [83]:
dataframe_metricas_produtos = dataframe_produtos.copy()
dataframe_metricas_produtos = dataframe_metricas_produtos.groupby(by="id_produto", as_index=False).agg(
    {
        "id_pedido": "count",
        "pontuacao": "mean",
    }
)

dataframe_metricas_produtos = dataframe_metricas_produtos.rename(
    columns={
        "id_pedido": "volume_vendas",
        "pontuacao": "media_avaliacao"
    }
)

dataframe_metricas_produtos.sample(n=5)

                             id_produto  volume_vendas  media_avaliacao
12866  63940cd00d32f9443e5371765ffc4d6a              1              5.0
3926   1d93a1a9ef04cca09f4737fc380e0d6e              1              5.0
5239   27a0edbc33200d89dfc1276a729dd5d4              1              5.0
16127  7c77aa8ae608782aac8e7728acff92fb              4              4.0
11301  56fa78f2a0c7d428e8aaa226dac0fbfb              1              5.0

In [84]:
dataframe_metricas_produtos.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_produto       32951 non-null  str
 1   volume_vendas    32951 non-null  int64
 2   media_avaliacao  32660 non-null  float64
dtypes: float64(1), int64(1), str(1)
memory usage: 772.4 KB

In [85]:
dataframe_metricas_produtos["media_avaliacao"] = (
    dataframe_metricas_produtos["media_avaliacao"].fillna(
        dataframe_metricas_produtos["media_avaliacao"].median()
    )
)

In [86]:
dataframe_metricas_produtos.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_produto       32951 non-null  str
 1   volume_vendas    32951 non-null  int64
 2   media_avaliacao  32951 non-null  float64
dtypes: float64(1), int64(1), str(1)
memory usage: 772.4 KB

In [87]:
dataframe_metricas_produtos.describe()

       volume_vendas  media_avaliacao
count   32951.000000     32951.000000
mean        3.418713         4.055222
std        10.619709         1.207830
min         1.000000         1.000000
25%         1.000000         3.666667
50%         1.000000         4.500000
75%         3.000000         5.000000
max       527.000000         5.000000

In [96]:
print(dataframe_metricas_produtos[dataframe_metricas_produtos["volume_vendas"] >= 10].shape)

(1919, 3)

In [88]:
dataframe_metricas_produtos.to_csv(PROCESSED_DATA_DIR / "produtos_metricas.csv", index=False)